use serde::{Deserialize, Serialize};

/// Parse fallback marker attached to narrative reports.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ParseWarning {
    /// Human-readable reason why the parser fell back.
    pub reason: String,
}

/// Advisory narrative generated from a scenario report.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct NarrativeReport {
    /// Short post-mortem summary.
    pub summary: String,
    /// Important events the analyst should look at first.
    pub key_events: Vec<String>,
    /// Commentary tied to the scenario's classified regime.
    pub regime_commentary: String,
    /// Suggested human follow-up actions.
    pub recommended_actions: Vec<String>,
    /// Present when the parser had to degrade to a fallback path.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parse_warning: Option<ParseWarning>,
}

impl NarrativeReport {
    /// Build a narrative report from the minimum required fields.
    #[must_use]
    pub fn new(
        summary: impl Into<String>,
        key_events: Vec<String>,
        regime_commentary: impl Into<String>,
        recommended_actions: Vec<String>,
    ) -> Self {
        Self {
            summary: summary.into(),
            key_events,
            regime_commentary: regime_commentary.into(),
            recommended_actions,
            parse_warning: None,
        }
    }
}

/// Severity of an anomaly flagged by the LLM.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Severity {
    /// Informational anomaly.
    Low,
    /// Noticeable anomaly with moderate impact.
    Medium,
    /// High-impact anomaly.
    High,
    /// System-threatening anomaly.
    Critical,
}

/// Structured anomaly identified in a scenario report.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AnomalyFlag {
    /// Fault type tied to the anomaly.
    pub fault_type: String,
    /// Node involved in the anomaly.
    pub node_id: String,
    /// Analyst-assigned severity.
    pub severity: Severity,
    /// Why this anomaly matters.
    pub explanation: String,
}

/// Human-readable next experiment suggestion.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ScenarioSuggestion {
    /// Name for the proposed scenario.
    pub name: String,
    /// Why the scenario is worth running.
    pub rationale: String,
    /// Human-readable hints about which faults to try.
    pub fault_hints: Vec<String>,
}

/// Explanation for replay divergence.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DivergenceExplanation {
    /// First visible divergence point.
    pub divergence_point: String,
    /// Most likely reason for the divergence.
    pub likely_cause: String,
    /// Human follow-up to narrow or fix the issue.
    pub suggested_fix: String,
}

/// Advisory output generated by an LLM provider for a scenario report.
///
/// # Example
///
/// ```rust
/// use malcolm_lens::{LensReport, NarrativeReport};
///
/// let report = LensReport::Narrative(NarrativeReport::new(
///     "Packet loss amplified into a visible outage",
///     vec!["packet_loss on node-a".to_owned()],
///     "The scenario stayed in the sensitive regime.",
///     vec!["Increase retry jitter and rerun the scenario".to_owned()],
/// ));
///
/// match report {
///     LensReport::Narrative(narrative) => {
///         assert!(narrative.summary.contains("outage"));
///     }
///     _ => unreachable!("example constructs a narrative report"),
/// }
/// ```
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", content = "payload", rename_all = "snake_case")]
pub enum LensReport {
    /// Post-mortem narrative.
    Narrative(NarrativeReport),
    /// Anomaly-focused report.
    Anomalies(Vec<AnomalyFlag>),
    /// Suggested next scenarios.
    Suggestions(Vec<ScenarioSuggestion>),
    /// Replay divergence explanation.
    Divergence(DivergenceExplanation),
}

#[cfg(test)]
mod tests {
    use super::{
        AnomalyFlag, DivergenceExplanation, LensReport, NarrativeReport, ParseWarning,
        ScenarioSuggestion, Severity,
    };

    fn assert_round_trip(report: &LensReport) -> Result<(), serde_json::Error> {
        let json = serde_json::to_string(report)?;
        let decoded: LensReport = serde_json::from_str(&json)?;
        assert_eq!(decoded, *report);
        Ok(())
    }

    #[test]
    fn narrative_round_trips_with_parse_warning() -> Result<(), serde_json::Error> {
        let mut narrative = NarrativeReport::new(
            "Latency spike pushed the service into a retry storm",
            vec!["latency_spike on api-1".to_owned()],
            "The scenario crossed into the chaotic regime.",
            vec!["Cap retry fan-out before rerunning".to_owned()],
        );
        narrative.parse_warning = Some(ParseWarning {
            reason: "response required manual recovery".to_owned(),
        });

        assert_round_trip(&LensReport::Narrative(narrative))
    }

    #[test]
    fn anomalies_round_trip() -> Result<(), serde_json::Error> {
        assert_round_trip(&LensReport::Anomalies(vec![AnomalyFlag {
            fault_type: "packet_loss".to_owned(),
            node_id: "edge-a".to_owned(),
            severity: Severity::High,
            explanation: "Loss concentrated on the leader path".to_owned(),
        }]))
    }

    #[test]
    fn suggestions_round_trip() -> Result<(), serde_json::Error> {
        assert_round_trip(&LensReport::Suggestions(vec![ScenarioSuggestion {
            name: "leader-thrash".to_owned(),
            rationale: "Probe whether clock skew compounds the retry storm".to_owned(),
            fault_hints: vec!["clock_jump".to_owned(), "latency_spike".to_owned()],
        }]))
    }

    #[test]
    fn divergence_round_trip() -> Result<(), serde_json::Error> {
        assert_round_trip(&LensReport::Divergence(DivergenceExplanation {
            divergence_point: "event 12".to_owned(),
            likely_cause: "Node ordering changed between runs".to_owned(),
            suggested_fix: "Stabilize node iteration before replay".to_owned(),
        }))
    }
}
